allprojects {
    group = 'io.lemadane.recordmaster'
    version = '1.0.0-rc3'

    repositories {
        mavenCentral()
    }
}

subprojects {
    afterEvaluate {
        if (plugins.hasPlugin('java')) {
            apply plugin: 'maven-publish'
            publishing {
                publications {
                    mavenJava(MavenPublication) {
                        from components.java
                    }
                }
            }
            if (project.hasProperty('testJavaVersion')) {
                tasks.withType(Test).configureEach {
                    javaLauncher = javaToolchains.launcherFor {
                        languageVersion = JavaLanguageVersion.of(project.property('testJavaVersion').toString())
                    }
                }
            }
        }
    }
}
